version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - 5672:5672
      - 15672:15672